version: '3'
services:
  postgres:
    image: postgres:9.6
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: quizlingo_server
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres